config/routes.rb
Rails.application.routes.draw do
  get '/', { to: 'ideas#index', as: 'root' }

  get '/signup', to: "users#new"
  post '/users', to: "users#create"

  get '/login', to: "sessions#new"

  get '/user/:id', { to: 'users#show', as: 'user' }

  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :memberships, only: [:create, :destroy, :index]
    resources :reviews, only: [:create, :destroy]
  end

  resource :session, only: [ :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea
    has_many :memberships, dependent: :destroy
    has_many :followers, through: :memberships, source: :idea
    has_secure_password

    validates(
        :username, 
        uniqueness: true,
        length: { minimum: 2 }
    )
    
    validates(
        :email, 
        presence: true, 
        uniqueness: true,
        format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    ) 
        
    validates(:password_digest, presence: true)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash[:danger] = @user.errors.full_messages.join(', ')
            redirect_to signup_path
        end
    end

    def show
        @user = User.find(params[:id])
        @likes = @user.likes
        @memberships = @user.memberships
    end

    private

    def user_params
       params.require(:user).permit(
           :username,
           :email, 
           :password, 
           :password_confirmation
        )
    end
end

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, local: true do |f| %>
    <div>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
        <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<h4 class="mt-4">Liked Ideas</h4>
<% @likes.each do |like| %>
    <p class="lead">
        <%= link_to "#{like.idea.title}", idea_path(like.idea) %> 
    </p>
<% end %>
<hr>
<h4>Ideas Joined</h4>
<% @memberships.each do |membership| %>
    <p class="lead">
        <%= link_to "#{membership.idea.title}", idea_path(membership.idea) %> 
    </p>
<% end %>

<%= link_to 'Home', ideas_path %>