config/routes.rb
Rails.application.routes.draw do
  get '/', { to: 'ideas#index', as: 'root' }

  get '/signup', to: "users#new"
  post '/users', to: "users#create"

  get '/login', to: "sessions#new"

  get '/user/:id', { to: 'users#show', as: 'user' }

  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :memberships, only: [:create, :destroy, :index]
    resources :reviews, only: [:create, :destroy]
  end

  resource :session, only: [ :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar-brand">
      <span>
        <%= link_to 'Idea Factory', ideas_path, { class: "btn btn-warning mx-1" } %>
        <%= link_to 'New Idea', new_idea_path, { class: "btn btn-success mx-1" } %>
      <span>
        <span>
          <% if user_signed_in? %>
            <span>Logged in as: <%= current_user.username %></span>
            <%= 
              link_to 'Sign Out', 
              session_path, 
              method: :delete,
              class: "btn btn-danger", 
              data: { confirm: "Log out?"}
            %>
          <% else %>
            <%= link_to 'Login', login_path, { class: "btn btn-primary mx-1" } %>
            <%= link_to 'Sign Up', signup_path, { class: "btn btn-success mx-1" } %>
          <% end %>
        </span>
      </nav>
      <hr>
        <% flash.each do |type, message| %>
              <div class="alert-<%= type %> mb-2">
                <%= message %>
              </div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>